In [1]:
import numpy as np

## 创建数组
### 1. array
array将输入数据（列表、元组、数组或其他序列类型）转换为ndarray.

In [11]:
# ndarray的所有元素必须是相同类型的
data1 = [6, 7.5, 8, 0, 1]
# 创建的array可以翻倍，相加减
arri1 = np.array(data1)
print arri1
# array元素的数据类型
print arri1.dtype

[ 6.   7.5  8.   0.   1. ]
float64


In [12]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arri2 = np.array(data2)
print arri2
# the number of rows
print arri2.ndim
# 数组的维度(rows, columns)
print arri2.shape
# 数据类型
print arri2.dtype

[[1 2 3 4]
 [5 6 7 8]]
2
(2, 4)
int64


### 2. np.zeros / np.ones / np.empty / np.arange

In [15]:
np.zeros((2, 3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [16]:
np.ones(10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [22]:
# 待查
np.empty((1, 1))

array([[ -2.68156159e+154]])

In [23]:
# arange是Python内置函数range的数组版
np.arange(10)

array(10)

## 创建矩阵
### eye / identity

In [27]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [28]:
np.identity(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])