In [1]:
import numpy as np

## 创建数组
### 1. array
array将输入数据（列表、元组、数组或其他序列类型）转换为ndarray.

In [11]:
# ndarray的所有元素必须是相同类型的
data1 = [6, 7.5, 8, 0, 1]
# 创建的array可以翻倍，相加减
arri1 = np.array(data1)
print arri1
# array元素的数据类型
print arri1.dtype

[ 6.   7.5  8.   0.   1. ]
float64


In [12]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arri2 = np.array(data2)
print arri2
# the number of rows
print arri2.ndim
# 数组的维度(rows, columns)
print arri2.shape
# 数据类型
print arri2.dtype

[[1 2 3 4]
 [5 6 7 8]]
2
(2, 4)
int64


### 2. np.zeros / np.ones / np.empty / np.arange

In [15]:
np.zeros((2, 3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [16]:
np.ones(10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [22]:
# 待查
np.empty((1, 1))

array([[ -2.68156159e+154]])

In [2]:
# arange是Python内置函数range的数组版
arr = np.arange(10)

### 3. copy
对数组切片的复制不成立，将数组的一部分赋值给新的数组后并对其修改，原数组也会变。需要复制数组需要显式使用copy

In [27]:
arr_slice = arr[5: 8]
arr_slice[1] = 12345
print arr
arr1 = arr[5: 8].copy()
arr1[1] = 64
print arr, arr1

[    0     1     1     3     4     5 12345     7     8     9]
[    0     1     1     3     4     5 12345     7     8     9] [ 5 64  7]


## 创建矩阵 eye / identity

In [27]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [28]:
np.identity(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

## 数据类型
NumPy的数据类型包括bool, object, string_, unicode_

### 设置数据类型dtype

In [12]:
arr = np.array([3.7, -1.2, -2.6], dtype=np.int32)
arr.dtype
print arr  # float --> int 小数部分直接截断

[ 3 -1 -2]


### 显示转换数据类型astype
注：调用astype会创建新的数组

In [16]:
bool_arr  = arr.astype(np.bool)
print bool_arr
str_arr = arr.astype(np.string_)
print str_arr
obj_arr = arr.astype(np.object)
print obj_arr
unicode_arr = arr.astype(np.unicode_)
print unicode_arr

[ True  True  True]
['3' '-1' '-2']
[3 -1 -2]
[u'3' u'-1' u'-2']


## 数组的运算
大小相等的数组之间的任何算术运算都会将运算应用到元素级
### 数组和数组的运算

In [28]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
print arr
print 'arr*arr=', arr*arr

[[ 1.  2.  3.]
 [ 4.  5.  6.]]
arr*arr= [[  1.   4.   9.]
 [ 16.  25.  36.]]


### 数组和标量的运算

In [20]:
1 / arr

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.25      ,  0.2       ,  0.16666667]])

## 数组的索引和切片
### 一维数组

In [3]:
# 可以索引
arr = np.arange(10)
print arr[5]
# 可以切片
print arr[5: 8]
# 可以直接赋值
arr[1:3] = 1
print arr

5
[5 6 7]
[0 1 1 3 4 5 6 7 8 9]


### 高纬度数组

In [17]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# 索引
print arr2d[0][0]
# or
print arr2d[0, 0]

# 切片: 现横轴，后竖轴
arr2d[:2, 1:]

1
1


array([[2, 3],
       [5, 6]])

In [14]:
arr3d = ([[[1, 2, 3], [4, 5, 6]],
          [[7, 8, 9], [10, 11, 12]]
         ])
print arr3d[0][0][1]

2


### 布尔索引

In [19]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob'])
names == 'Bob'

array([ True, False, False,  True], dtype=bool)

In [25]:
data = np.random.randn(4, 4)
print data

[[-1.53354898 -2.02888469  2.13655498 -0.43369054]
 [-0.05142364 -0.12692358  0.51601766  0.59038789]
 [ 0.10463292 -0.91916676  0.50385485  0.1399287 ]
 [ 0.13054936 -0.49385433  0.37551156  1.20707999]]


In [28]:
data[names == 'Bob', 1]

array([-2.02888469, -0.49385433])

In [30]:
data[data < 0] = 0
data

array([[ 0.        ,  0.        ,  2.13655498,  0.        ],
       [ 0.        ,  0.        ,  0.51601766,  0.59038789],
       [ 0.10463292,  0.        ,  0.50385485,  0.1399287 ],
       [ 0.13054936,  0.        ,  0.37551156,  1.20707999]])

### 花式索引
花式索引会将数据复制到新数组中

In [40]:
arr = arr2d
print arr[[2, 1, 0]]

# equal to
print arr[[-1, -2, -3]]

[[7 8 9]
 [4 5 6]
 [1 2 3]]
[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [49]:
arr = np.arange(32).reshape((8, 4))
print arr
arr[[1, 5, 7, 2],[0, 3, 1, 2]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


array([ 4, 23, 29, 10])

## 数组转置与轴对换

In [54]:
arr = np.arange(12).reshape((3, 4))
print arr
print arr.T
# 数组的乘法
print np.dot(arr.T, arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 80  92 104 116]
 [ 92 107 122 137]
 [104 122 140 158]
 [116 137 158 179]]


## 数组的原子操作

In [63]:
x1 = np.arange(9.0).reshape((3, 3))
x2 = np.arange(3.0)
print x1, x2
np.add(x1, x2)

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]] [ 0.  1.  2.]


array([[  0.,   2.,   4.],
       [  3.,   5.,   7.],
       [  6.,   8.,  10.]])

## 利用数组进行数据处理
### list comprehension

In [67]:
xarr = np.array([1, 2, 3, 4, 5])
yarr = np.array([6, 7, 8, 9, 10])
cond = np.array([True, False, True, True, False])
result = np.where(cond, xarr, yarr)
result

array([ 1,  7,  3,  4, 10])

In [69]:
arr = np.random.randn(4, 4)
np.where(arr > 0, 2, -2)

array([[-2,  2, -2,  2],
       [ 2,  2, -2, -2],
       [-2, -2,  2,  2],
       [-2, -2,  2,  2]])

## 数学和统计方法
可以通过数组上的一组数学函数对整个数组或某个轴向的数据进行：
1. 统计计算: sum, mean. std(标准差)

### np.linspace